#sdk: "/Users/nishima/.rvm/gems/ruby-1.9.3-p194@kyusu/gems/rhodes-3.3.3"
sdkversion: 3.3.3
name: Tabbar
version: 1.0
vendor: rhomobile
build: debug
bbver: 4.6
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator5.0
  provisionprofile:
  codesignidentity:
  entitlements:
  BundleIdentifier: com.rhomobile.tabbar
  BundleURLScheme: tabbar
wp:
  productid: '57235760-bc4b-012f-2a57-1040f37b2b30'
symbian:
  uid: '0xe9c760ec'
android:
  version: 2.1

extensions: ["json", "another-extension"]
